global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus

    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090
  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: app-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: 
          - app-server:8081